# NeON Build File (http://github.com/c4s4/neon)

default: run
extends:
- c4s4/build/golang.yml

properties:
  NAME:     'goride'
  VERSION:  '1.0.0'
  # algo : 'sort' or 'value'
  ALGO:     'value'
  RUN_ARGS: [=ALGO, 'examples', =BUILD_DIR]

targets:

  run:
    doc: 'Run ride challenge'
    depends: clean
    steps:
    - mkdir: =BUILD_DIR
    - super:
