# NeON Build File (http://github.com/c4s4/neon)

default: run
extends:
- c4s4/build/golang.yml
- c4s4/build/release.yml

properties:
  NAME:     'goride'
  VERSION:  '1.0.0'
  RUN_ARGS: ['examples', =BUILD_DIR]
  A_START:  0.7
  A_END:    0.9
  A_STEP:   0.01
  B_START:  2.1
  B_END:    2.3
  B_STEP:   0.01
  THREADS:  =_NCPU
  COLSEP:   ' '

targets:

  run:
    doc: 'Run ride challenge'
    depends: clean
    steps:
    - mkdir: =BUILD_DIR
    - super:

  search:
    doc: Search for best alpha and beta values
    depends: clean
    steps:
    - mkdir: =BUILD_DIR
    - |
      couples = []
      for a=A_START; a<=A_END; a+=A_STEP {
        for b=B_START; b<=B_END; b+=B_STEP {
          couples += [[a, b]]
        }
      }
      report = ""
    - threads: =THREADS
      input:   =couples
      steps:
      - 'alpha = _input[0]'
      - 'beta  = _input[1]'
      - $: ['go', 'run', 'goride.go', '-alpha', '={alpha}', '-beta', '={beta}', 'examples', =BUILD_DIR]
        3x: true
      - read: '={BUILD_DIR}/README'
        to:   result
      - |
        lines = split(result, "\n")
        last = lines[len(lines)-2]
        parts = split(last, " ")
        score = parts[len(parts)-1]
      - '_output = toString(alpha)+COLSEP+toString(beta)+COLSEP+toString(score)'
      - print: =_output
    - write: '={BUILD_DIR}/results.dat'
      text:  ={join(_output, "\n")}

  gnuplot:
    doc: Run gnuplot to see result
    steps:
    - write: '={BUILD_DIR}/gnuplot.plt'
      text: |
        set dgrid3d 50,50 qnorm 2
        set hidden3d
        splot 'results.dat' with lines palette
    - chdir: =BUILD_DIR
    - $: ['gnuplot', '-p', 'gnuplot.plt']
